### ISSUE TITLE
Where is the Source Code?

### ISSUE THREAD

**Issue by tofi86** [colameo/JDL-Bridge#2]
Hi,

I stumbled over your project when searching for a JDL to PlantUML conversion solution in https://github.com/jhipster/jhipster-core/issues/422

I really like to use this util, but I'd like to review the source code first and it's missing in the repo. Any chance to up the code?

Danke! /Tobias

**Comment by colameo** [comment]
this tool is (at least for the moment) closed source. however, you can submit a change or feature request if you need improvements ...

**Comment by colameo** [comment]
i'm closing this issue
